### ISSUE TITLE
Workaround for cloudflare protected websites

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD#1715]
**Preparation**
- Install [python](https://www.python.org/). Enable "Add python.exe to PATH" from the python installation screen
- Open the file in `{FMD2 Directory}\lua\websitebypass\websitebypass_config.json` and set `use_webdriver` to `true`

**Method 1: FlareSolverr (64-bit only)**
- Install python package `requests` with `pip install requests`
- Download [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr). Extract it somewhere
- Run `flaresolverr.exe` and wait for it to say `Serving on http://0.0.0.0:8191`
- Paste the site url into FMD2 to get the manga info and chapters
- Check Flaresolverr if any incoming requests are made and if they are solving the challenge and getting a `200 OK` response

To test if everything is working properly, run in CMD or PowerShell from your `{FMD2 Directory}\lua\websitebypass` directory the following command: `python cloudflare.py "https://dragontea.ink"` to see if any errors pop up or not

**Method 2: rookiepy (Python 3.12 only)**
- Install python package `rookiepy` with `pip install rookiepy`
- Open the site you want to get cookies for in any of the following browsers: `Chrome, Edge, Firefox, Opera, Opera GX`
- Close the tab or browser to ensure the cookies are saved to file
- Paste the site url into FMD2 to get the manga info and chapters
- Open FMD2 log to see if errors pop up or not. You can ignore `Please make sure FlareSolverr is running.`
- Alternatively check `Options -> Websites -> Advanced` and search for your site to see if cookies were applied correctly
- If cookies were applied correctly but the manga info doesn't load, make sure you've recently visited the site in your browser and the cookies haven't expired

\* Currently has issues decrypting cookies from Chrome and doesn't work. Use an alternative browser until the issue is fixed

To test if everything is working properly, run in CMD or PowerShell from your `{FMD2 Directory}\lua\websitebypass` directory the following command: `python cloudflare.py "https://dragontea.ink"` to see if any errors pop up or not

**Manual workaround**
For Chromium based browser
- Visit website and select any manga in browser -> press `F12` -> select `Network` tab
- In the `Name` section, select the first one -> see `Headers` tab and search for `cookie` and `user-agent`, copy all of it
- In FMD2, go to `Options -> Websites -> Advanced -> {Website Name}`, change `Enabled` option to `True`, paste the `cookie` and `user-agent` from browser

**Troubleshooting**
If you see the cookies disappear in FMD2, try using a VPN and try multiple different servers.
If that also doesn’t work, you’ll just have to wait for the site to lower its protection.

**Comment by xavimaa** [comment]
Hello,

Thank you for this very well-explained guide!

Is there a possibility to use flaresolverr hosted on Docker?

I apologize if this question requires opening a new issue.

Thanks again 🙏

**Comment by Slasar41** [comment]
Sorry, I don't use Docker.

**Comment by NhKPaNdA** [comment]
> Is there a possibility to use flaresolverr hosted on Docker?

I tried out using a Docker and it did work in the end. I had to make sure the docker was hosting through the vm into the host machine so the cloudflare bypass could correctly connect to it through localhost.

Even though it does work I realised it does take a lot longer per connection and will generally timeout with the default 60s when connecting to the docker instead of the .exe or cmd run python which roughly takes ~20s.

**Comment by molitar** [comment]
Not working.

C:\DOS\fmd 2.0\lua\websitebypass>python customcloudflare.py "https://dragontea.ink"
Error: Error solving the challenge. Timeout after 60.0 seconds.

> 2025-02-13 18:23:07 INFO     FlareSolverr 3.3.21
> 2025-02-13 18:23:07 INFO     Testing web browser installation...
> 2025-02-13 18:23:07 INFO     Platform: Windows-10-10.0.19045-SP0
> 2025-02-13 18:23:07 INFO     Chrome / Chromium path: C:\DOS\fmd 2.0\lua\websitebypass\flaresolverr\chrome\chrome.exe
> 2025-02-13 18:23:07 INFO     Chrome / Chromium major version: 123
> 2025-02-13 18:23:07 INFO     Launching web browser...
> 2025-02-13 18:23:11 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
> 2025-02-13 18:23:11 INFO     Test successful!
> 2025-02-13 18:23:11 INFO     Serving on http://0.0.0.0:8191
> 2025-02-13 18:23:25 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://dragontea.ink', 'returnOnlyCookies': True, 'maxTimeout': 60000}
> 2025-02-13 18:23:26 INFO     Challenge detected. Title found: Just a moment...
> 2025-02-13 18:24:29 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
> 2025-02-13 18:24:29 INFO     Response in 63.205 s
> 2025-02-13 18:24:29 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error

![Image](https://github.com/user-attachments/assets/bf2bcc1c-f858-400b-b62b-d13e62f81e89)

![Image](https://github.com/user-attachments/assets/fa596ec6-ef8d-45f2-90e4-9757b742ff2c)

**Comment by NhKPaNdA** [comment]
That's a known issue with flaresolver as mentioned in method 1a. Follow the fork for a working version.

**Comment by molitar** [comment]
> That's a known issue with flaresolver as mentioned in method 1a. Follow the fork for a working version.

Did I do something wrong I had a chance to come back and try method  1a and I got this error.

```
PS C:\FlareSolverr-nodriver-support> python src/flaresolverr.py
Traceback (most recent call last):
  File "C:\FlareSolverr-nodriver-support\src\flaresolverr.py", line 8, in <module>
    from bottle import run, response, Bottle, request, ServerAdapter
ModuleNotFoundError: No module named 'bottle'
PS C:\FlareSolverr-nodriver-support>
```

**Comment by Qizmo** [comment]
Hi, I was told to use manual workaround in the pinned issue.
https://github.com/dazedcat19/FMD2/issues/2080

So I try everything and also download chromium instead of chrome. However after I put in cookie and user-agent from browser then save, the cookie keep disappearing. 

![Image](https://github.com/user-attachments/assets/1b357198-ea2b-4d26-ab02-54f48fd5f7c2)
First pic I put in both cookie and user-agent, then save and restart FMD2.

![Image](https://github.com/user-attachments/assets/605a636e-6eb8-4c86-bdd7-d40668bad28b)
This picture show that the cookie keep disappearing.
So Even after several trials, I still can't access the mgeko.cc What must I do?

**Comment by Qizmo** [comment]
Next I try following: Method 1: FlareSolverr (64-bit only)
I follow everything until: Paste the site url into FMD to get the manga info and chapters

![Image](https://github.com/user-attachments/assets/c5439048-276c-4597-99a1-dc1bf8233735)
I wait for it to say Serving on http://0.0.0.0:8191
Then Paste the manga site url into FMD to get the manga info and chapters as above.
But I still got nothing.

Edit: Somehow it started downloading again. ^^

**Comment by NhKPaNdA** [comment]
> Hi, I was told to use manual workaround in the pinned issue. [#2080](https://github.com/dazedcat19/FMD2/issues/2080)
> 
> So I try everything and also download chromium instead of chrome. However after I put in cookie and user-agent from browser then save, the cookie keep disappearing.

Cookies and user agent are very tightly tied together. Make sure they're as new as possible from your browser (maybe ctrl + f5 to refresh) and probably try different mainstream browsers if one fails. Chrome, Edge, FireFox, etc.

FMD will clear the cookies and user agent if the ones that were there failed to connect which is why you're seeing them being cleared.

> Next I try following: Method 1: FlareSolverr (64-bit only) I follow everything until: Paste the site url into FMD to get the manga info and chapters

Flaresolverr is not getting any requests. Try testing the python script out like in the main post:
> To test if everything is working properly, run in CMD or Powershell from your `{FMD Directory}\lua\websitebypass` directory the following command: `python customcloudflare.py "https://dragontea.ink"` to see if any errors pop up or not

It's possible you're missing a python module needed to run the script.

If you get any timeouts with Flaresolverr on requests then try out method 1a.

**Comment by Qizmo** [comment]
@NhKPaNdA  IT resolved by itself already. Guess Slasar41 did something with the app. 
Thank you very much ^^

**Comment by Slasar41** [comment]
@Qizmo I'm not doing anything.
The site turned off the protection so there's no need for a workaround.

**Comment by hiroshil** [comment]
> Hi, I was told to use manual workaround in the pinned issue. [#2080](https://github.com/dazedcat19/FMD2/issues/2080)
> 
> So I try everything and also download chromium instead of chrome. However after I put in cookie and user-agent from browser then save, the cookie keep disappearing.
> 
> ![Image](https://github.com/user-attachments/assets/1b357198-ea2b-4d26-ab02-54f48fd5f7c2) First pic I put in both cookie and user-agent, then save and restart FMD2.
> 
> ![Image](https://github.com/user-attachments/assets/605a636e-6eb8-4c86-bdd7-d40668bad28b) This picture show that the cookie keep disappearing. So Even after several trials, I still can't access the mgeko.cc What must I do?

I did the same thing, but I used the [Get cookies.txt LOCALLY](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) extension to export Cookie Header String and pasted it with User-Agent into Options. Everything worked fine.

**Comment by molitar** [comment]
> > Hi, I was told to use manual workaround in the pinned issue. [#2080](https://github.com/dazedcat19/FMD2/issues/2080)
> > So I try everything and also download chromium instead of chrome. However after I put in cookie and user-agent from browser then save, the cookie keep disappearing.
> > ![Image](https://github.com/user-attachments/assets/1b357198-ea2b-4d26-ab02-54f48fd5f7c2) First pic I put in both cookie and user-agent, then save and restart FMD2.
> > ![Image](https://github.com/user-attachments/assets/605a636e-6eb8-4c86-bdd7-d40668bad28b) This picture show that the cookie keep disappearing. So Even after several trials, I still can't access the mgeko.cc What must I do?
> 
> I did the same thing, but I used the [Get cookies.txt LOCALLY](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) extension to export Cookie Header String and pasted it with User-Agent into Options. Everything worked fine.

Thanks worked great and I am using that Get cookies.txt LOCALLY inside of the new Floorp browser you can enable using Chrome Extensions in Floorp which is based on Firefox.  So now no longer locked to Chrome.

**Comment by sleepy1841986** [comment]
Paste the site url into FMD2 to get the manga info and chapters
    Check Flaresolverr if any incoming requests are made and if they are solving the challenge and getting a 200 OK response

To test if everything is working properly, run in CMD or PowerShell from your {FMD2 Directory}\lua\websitebypass directory the following command: python customcloudflare.py "https://dragontea.ink" to see if any errors pop up or not


Hy stuck at this step
I copy paste one of my URL of sushiscan still blank
 And I have no request and test command work fine if i rename it to customcloudfare -> cloudfare
Because the file is name cloudfare and FMD want this one

But still nothing with sushi scan, blank chapter


Any idea ^^ ?

Thanks for all

**Comment by molitar** [comment]
OK I had to use AI to fix the cloudflare.py and cloudflare.lua but it works now just fine.  I have attached the two files that fixes Flaresolverr.exe.  

[cloudflare.zip](https://github.com/user-attachments/files/24983038/cloudflare.zip)

Had to zip them up as otherwise I could not upload lua file types.

Updated files as I forgot to include the cloudflare_runner.bat.

Fixes: the script will first try to get the cookies by using rookiepy which is faster than flaresolverr but there are a few sites that rookiepy does not work on.  If rookiepy fails than it uses the cloudflare_runner.bat to pass it onto flaresolverr for it to solve. You can see FMD working with Flaresolverr below. 

<img width="2563" height="1309" alt="Image" src="https://github.com/user-attachments/assets/10466679-1362-4e9c-87d1-9faeab03a55b" />

I also uploaded here my get_cookies.bat that will search 4 different browser for cookies to the site you want to open. It supports browsers: Floorp, Firefox, Edge, and Chrome. AI can add additional browser that you use if different by dropping the cloudflare.py code into the AI chat and ask it to add whatever browser you use.  Why would you want to use this tool as it formats the cookie 100% the way FMD wants it to be.  

Get_Cookies.bat how to use
1. Extract the 3 files into their own folder as the cloudflare.py is custom for this tool
2. Double click to launch the batch file it will open up a pop up cmd console
3. Simply paste or type in the link for site you want cookie for like https://likemanga.ink
4. It will search your system for any of the 4 browsers install and look for the cookie you use to open that site with
5. It will than grab the cookie in the form FMD wants and copy to the clipboard
6. It will show you in the console window the useragent string to use as most websites don't show the full agent which causes FMD to fail to open cloudflare site
7. Press enter on the console window to close. 

I have uploaded a couple screenshots of the get_cookies tool one showing site not open in any browser so no cookies found. One where it found cookies and if you have opened it in many browsers it will pick a unique cookie I had 9 cookies for the one site when opened in all 4 browsers.  This is also where extensions fail as they will grab duplicates confusing FMD. 

<img width="1034" height="525" alt="Image" src="https://github.com/user-attachments/assets/e7aa45b3-d2af-4f10-bb22-5ed259ec0269" />

<img width="2016" height="584" alt="Image" src="https://github.com/user-attachments/assets/96410a92-0880-426a-a864-e1bb18638230" />

[get_cookies.zip](https://github.com/user-attachments/files/24983082/get_cookies.zip)

**Comment by formigao** [comment]
> OK I had to use AI to fix the cloudflare.py and cloudflare.lua but it works now just fine. I have attached the two files that fixes Flaresolverr.exe.
> 
> [cloudflare.zip](https://github.com/user-attachments/files/24983038/cloudflare.zip)
> 
> Had to zip them up as otherwise I could not upload lua file types.
> 
> Updated files as I forgot to include the cloudflare_runner.bat.
> 
> Fixes: the script will first try to get the cookies by using rookiepy which is faster than flaresolverr but there are a few sites that rookiepy does not work on. If rookiepy fails than it uses the cloudflare_runner.bat to pass it onto flaresolverr for it to solve. You can see FMD working with Flaresolverr below.
> 
> <img alt="Image" width="2000" height="1309" src="https://private-user-images.githubusercontent.com/16074561/543280279-10466679-1362-4e9c-87d1-9faeab03a55b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE1NDU3MTcsIm5iZiI6MTc3MTU0NTQxNywicGF0aCI6Ii8xNjA3NDU2MS81NDMyODAyNzktMTA0NjY2NzktMTM2Mi00ZTljLTg3ZDEtOWZhZWFiMDNhNTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE5VDIzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMjZhZGI5OTY5MTZmMTIyZjAxODIxY2EwNGEwNTRkMTMzODMwMjAwNGQwZjMxYTBlYjlhMGE5Y2E0ZDJjMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cUrz-arB38Y37FyDqjv623OK0P4zb3H9LmH5w-nVv9Q">
> I also uploaded here my get_cookies.bat that will search 4 different browser for cookies to the site you want to open. It supports browsers: Floorp, Firefox, Edge, and Chrome. AI can add additional browser that you use if different by dropping the cloudflare.py code into the AI chat and ask it to add whatever browser you use. Why would you want to use this tool as it formats the cookie 100% the way FMD wants it to be.
> 
> Get_Cookies.bat how to use
> 
> 1. Extract the 3 files into their own folder as the cloudflare.py is custom for this tool
> 2. Double click to launch the batch file it will open up a pop up cmd console
> 3. Simply paste or type in the link for site you want cookie for like https://likemanga.ink
> 4. It will search your system for any of the 4 browsers install and look for the cookie you use to open that site with
> 5. It will than grab the cookie in the form FMD wants and copy to the clipboard
> 6. It will show you in the console window the useragent string to use as most websites don't show the full agent which causes FMD to fail to open cloudflare site
> 7. Press enter on the console window to close.
> 
> I have uploaded a couple screenshots of the get_cookies tool one showing site not open in any browser so no cookies found. One where it found cookies and if you have opened it in many browsers it will pick a unique cookie I had 9 cookies for the one site when opened in all 4 browsers. This is also where extensions fail as they will grab duplicates confusing FMD.
> 
> <img alt="Image" width="1034" height="525" src="https://private-user-images.githubusercontent.com/16074561/543280029-e7aa45b3-d2af-4f10-bb22-5ed259ec0269.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE1NDU3MTcsIm5iZiI6MTc3MTU0NTQxNywicGF0aCI6Ii8xNjA3NDU2MS81NDMyODAwMjktZTdhYTQ1YjMtZDJhZi00ZjEwLWJiMjItNWVkMjU5ZWMwMjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE5VDIzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZmFjOGEwZjY5NTAyMzdkNjU5NjlhZmZkZjExOTU4ZThjYzMzMjY3OWQ1YTBmZDg5Y2M3ZGNkZTljMGMwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.baYbHCkp_KtOLKJds_hIe2t2vtEEgttNg-MaicqfphY"> <img alt="Image" width="2000" height="584" src="https://private-user-images.githubusercontent.com/16074561/543280079-96410a92-0880-426a-a864-e1bb18638230.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE1NDU3MTcsIm5iZiI6MTc3MTU0NTQxNywicGF0aCI6Ii8xNjA3NDU2MS81NDMyODAwNzktOTY0MTBhOTItMDg4MC00MjZhLWE4NjQtZTFiYjE4NjM4MjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE5VDIzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNWNlN2UwMjJhMzgzYjJkZDMzYzY2MThmNGUzZmE1NzU5Y2JkN2FiZjZmZjFkNzI3NGY5OTM3OGM3OTdkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EOIPR7HuT-YKaBOs3qQjfJi9TaQkg5ccvbpSY-us3gA">
> [get_cookies.zip](https://github.com/user-attachments/files/24983082/get_cookies.zip)

im getting this error with your file : [Searching...]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\get_cookies\cloudflare.py", line 6, in <module>
    import pyperclip
ModuleNotFoundError: No module named 'pyperclip'

**Comment by molitar** [comment]
> import pyperclip

Use this command to make sure the pyperclip is found.

pip install pyperclip

if that does not work than use this command.

python -m pip install pyperclip

**Comment by formigao** [comment]
I'm getting nothing now but its working. flare also have nothing there
![Image](https://github.com/user-attachments/assets/6da27d50-d88d-4a49-823b-21481906934c)
